# Generated by Django 4.2.7 on 2026-03-25 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('two_fa_code', models.CharField(blank=True, max_length=100, verbose_name='2FA Secret/Code')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True)),
                ('profile_id', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('recovery_email', models.EmailField(blank=True, max_length=254)),
                ('proxy', models.CharField(blank=True, help_text='Proxy IP:PORT', max_length=200)),
                ('user_agent', models.TextField(blank=True)),
                ('cookies', models.TextField(blank=True, help_text='Account cookies JSON')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('checkpoint', 'Checkpoint'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fb_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('page_id', models.CharField(blank=True, max_length=100)),
                ('page_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('business', 'Business'), ('entertainment', 'Entertainment'), ('news', 'News & Media'), ('community', 'Community'), ('brand', 'Brand'), ('artist', 'Artist'), ('public_figure', 'Public Figure'), ('education', 'Education'), ('nonprofit', 'Non-Profit'), ('sports', 'Sports'), ('tech', 'Technology'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('total_reels', models.PositiveIntegerField(default=0)),
                ('total_videos', models.PositiveIntegerField(default=0)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('cover_photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('restricted', 'Restricted'), ('unpublished', 'Unpublished'), ('banned', 'Banned')], default='active', max_length=20)),
                ('monetization_enabled', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='facebook.facebookaccount')),
            ],
            options={
                'db_table': 'fb_pages',
                'ordering': ['-followers_count'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('post_created', 'Post Created'), ('reel_created', 'Reel Created'), ('page_updated', 'Page Updated'), ('stats_updated', 'Stats Updated'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='facebook.facebookaccount')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='facebook.facebookpage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('new_followers', models.IntegerField(default=0)),
                ('lost_followers', models.IntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('post_reach', models.PositiveIntegerField(default=0)),
                ('post_impressions', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_posts', models.PositiveIntegerField(default=0)),
                ('new_reels', models.PositiveIntegerField(default=0)),
                ('new_videos', models.PositiveIntegerField(default=0)),
                ('new_likes', models.IntegerField(default=0)),
                ('total_reactions', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='facebook.facebookpage')),
            ],
            options={
                'db_table': 'page_daily_stats',
                'ordering': ['-date'],
                'unique_together': {('page', 'date')},
            },
        ),
    ]
